import React from 'react';

import Head from 'next/head';

import styles from '../../../styles/pages/home.module.scss';

import { textBoxContent, textBoxTitle } from '../../../dummy/text';

import TextBox from '../../components/text-box/TextBox.component';
import Avatar from '../../components/avatar/Avatar.component';
import PanelsList from '../../components/panels/list/PanelsList';
import Footer from '../../components/footer/Footer.component';

const MainLayout: React.FC = ({ children }) => {
  return (
    <div>
      <>
        <Head>
          <title>arslanoov.red</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div className={`container ${styles['about-container']}`}>
            <div className={styles.box}>
              <TextBox title={textBoxTitle} content={textBoxContent} />
            </div>
            <div className={styles.avatar}>
              <Avatar />
              <PanelsList />
            </div>
          </div>

          {children}
        </main>

        <Footer />
      </>
    </div>
  );
};

export default MainLayout;
