import React from 'react';

import Head from 'next/head';

import styles from './main-layout.module.scss';

import { textBoxContent, textBoxTitle } from '@/dummy/text';

import TextBox from '@/ui/components/text-box/TextBox.component';
import Avatar from '@/ui/components/avatar/Avatar.component';
import PanelsListComponent from '@/ui/components/panels/list/PanelsList.component';
import Footer from '@/ui/components/footer/Footer.component';

const MainLayout: React.FC = ({ children }) => {
  return (
    <div>
      <Head>
        <title>arslanoov.red</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.layout}>
        <main>
          <div className={`container ${styles['about-container']}`}>
            <div className={styles.box}>
              <TextBox title={textBoxTitle} content={textBoxContent} />
            </div>
            <div className={styles.avatar}>
              <Avatar />
              <PanelsListComponent />
            </div>
          </div>

          {children}
        </main>

        <Footer />
      </div>
    </div>
  );
};

export default MainLayout;
