import React from 'react';
import Head from 'next/head';

import Header from '@/ui/components/header/Header.component';

import styles from './main-layout.module.scss';

const MainLayout: React.FC = ({ children }) => {
  return (
    <div>
      <Head>
        <title>arslanoov.red</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.layout}>
        <Header />

        <main>
          {children}
        </main>
      </div>
    </div>
  );
};

export default MainLayout;
