import type { NextPage } from 'next';

import Head from 'next/head';

import ContentList from '../../components/content-list/list/ContentList';
import Footer from '../../components/footer/Footer.component';

import styles from '../../styles/pages/posts.module.scss';
import ContentMoreButton from '../../components/content-list/more-button/ContentMoreButton';

const Posts: NextPage = () => {
  return (
    <>
      <Head>
        <title>arslanoov.red</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={'container'}>
          <div className={styles.content}>
            <ContentMoreButton link='/' text={'Back'} />
            <ContentList vertical={false} title="Recent posts" />
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
};

export default Posts;
