import type { NextPage } from 'next';

import Head from 'next/head';

import styles from '../styles/pages/home.module.scss';

import { textBoxTitle, textBoxContent } from '../dummy/text';

import TextBox from '../components/text-box/TextBox.component';
import Avatar from '../components/avatar/Avatar.component';
import Footer from '../components/footer/Footer.component';
import PanelsList from '../components/panels/list/PanelsList';
import ContentList from '../components/content-list/list/ContentList';
import ContentMoreButton from '../components/content-list/more-button/ContentMoreButton';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>arslanoov.red</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={`container ${styles['about-container']}`}>
          <div className={styles.box}>
            <TextBox title={textBoxTitle} content={textBoxContent} />
          </div>
          <div className={styles.avatar}>
            <Avatar />
            <PanelsList />
          </div>
        </div>

        <div className={`container ${styles['content-container']}`}>
          <div className={styles.blog}>
            <ContentList title="Recent posts" vertical={true} />
            <div className={styles.button}>
              <ContentMoreButton link='/blog/posts' />
            </div>
          </div>

          <div className={styles.works}>
            <ContentList title="Portfolio" vertical={true} />
            <div className={styles.button}>
              <ContentMoreButton link='/portfolio' />
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
};

export default Home;
