import type { NextPage } from 'next'

import Head from 'next/head'
import Image from 'next/image'

import TextBox from '../components/text-box/TextBox.component'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TextBox
          content={
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit." +
            "Accusantium cum delectus est magnam minima modi nam quidem, quos repudiandae." +
            "Aliquid animi aperiam, autem corporis delectus doloremque eligendi error excepturi" +
            "impedit ipsam ipsum labore laborum magnam nam natus officia officiis" +
            "provident quaerat quasi quia quidem recusandae, repellat temporibus ullam, vero voluptatem?"
          }
        />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
